/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 08-Apr-2011, 12:18:04
 */
package shef.mt.enes;

import javax.swing.*;
import java.util.*;
import javax.swing.table.*;
import java.io.*;

/**
 *
 * @author cat
 */
public class MainApp extends javax.swing.JFrame {

    private static String workDir;
    private static String sourceFile = "";
    private static String targetFile = "";
    private static String mode = "bb";
    private static boolean log = true;
    private static boolean rebuild = false;
    private static shef.mt.util.PropertiesManager propManager;
    private static String configFile = null;
    private static boolean firstRun = false;
    private static String TOOLS = "tools";

    /**
     * Creates new form NewJFrame
     */
    public MainApp() {
        String conf = System.getProperty("user.home");
        String userFile = conf + File.separator + ".mtfeatures";
        File f = new File(userFile);
        if (f.exists()) {
            readUserConfig();
        } else {
            firstRun = true;
            workDir = System.getProperty("user.dir");
        }

        propManager = new shef.mt.util.PropertiesManager();
        initComponents();
        if (firstRun) {
            jDialogConfig.setVisible(true);
        }
    }

    public void readUserConfig() {
        try {
            String conf = System.getProperty("user.home");
            String userFile = conf + File.separator + ".mtfeatures";
            BufferedReader fr = new BufferedReader(new FileReader(userFile));
            String line = "";
            while (line.length() == 0 && line != null) {
                line = fr.readLine();
            }
            workDir = line.split("=")[1];
            while (line.length() == 0 && line != null) {
                line = fr.readLine();
            }
            configFile = line.split("=")[1];
        } catch (Exception e) {
            firstRun = true;
            workDir = System.getProperty("user.dir");
        }
    }

    public void saveUserConfig() {
        try {
            String conf = System.getProperty("user.home");
            String userFile = conf + File.separator + ".mtfeatures";
            FileWriter fw = new FileWriter(userFile);
            fw.write("working folder = " + workDir + "\r\n");
            fw.write("config = " + configFile);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialogRun = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioGB = new javax.swing.JRadioButton();
        jRadioBBGB = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioBB = new javax.swing.JRadioButton();
        jCheckBoxLog = new javax.swing.JCheckBox();
        jTextSourceFile = new javax.swing.JTextField(sourceFile);
        jTextTargetFile = new javax.swing.JTextField(targetFile);
        jButtonBrowseSource = new javax.swing.JButton();
        jButtonBrowseTarget = new javax.swing.JButton();
        jRadioIBM = new javax.swing.JRadioButton();
        jRadioMOSES = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonRun = new javax.swing.JButton();
        jDialogConfig = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonSaveAs = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextDir = new javax.swing.JTextField(workDir);
        jButtonDirChooser = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextSourceLang = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JTextTargetLang = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextDefInput = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextDefOutput = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextDefLog = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboLang = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLangProp = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTools = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jSplitPaneText = new javax.swing.JSplitPane();
        jScrollPaneSource = new javax.swing.JScrollPane();
        jTextPaneSource = new javax.swing.JTextPane();
        jScrollPaneTarget = new javax.swing.JScrollPane();
        jTextPaneTarget = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRun = new javax.swing.JMenu();
        jMenuItemRunSimple = new javax.swing.JMenuItem();
        jMenuItemRunClean = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemConfig = new javax.swing.JMenuItem();
        jMenuItemClean = new javax.swing.JMenuItem();

        jDialogRun.setTitle("Runtime arguments");
        jDialogRun.setAlwaysOnTop(true);
        jDialogRun.setMinimumSize(new java.awt.Dimension(550, 425));
        jDialogRun.setModal(true);
        jDialogRun.setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(547, 425));

        jLabel1.setText("Source file");

        jLabel2.setText("Target file");

        jRadioGB.setFont(new java.awt.Font("Tahoma", 0, 10));
        jRadioGB.setLabel("Glassbox features only");
        jRadioGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGBActionPerformed(evt);
            }
        });

        jRadioBBGB.setFont(new java.awt.Font("Tahoma", 0, 10));
        jRadioBBGB.setText("Blackbox and glassbox features");
        jRadioBBGB.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioBBGB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jRadioBBGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBBGBActionPerformed(evt);
            }
        });

        jLabel3.setText("Mode");

        jRadioBB.setFont(new java.awt.Font("Tahoma", 0, 10));
        jRadioBB.setSelected(true);
        jRadioBB.setLabel("Blackbox features only");
        jRadioBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBBActionPerformed(evt);
            }
        });

        jCheckBoxLog.setSelected(true);
        jCheckBoxLog.setActionCommand("Enable logging");
        jCheckBoxLog.setLabel("Enable logging");
        jCheckBoxLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLogActionPerformed(evt);
            }
        });

        jButtonBrowseSource.setText("...");
        jButtonBrowseSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseSourceActionPerformed(evt);
            }
        });

        jButtonBrowseTarget.setText("...");
        jButtonBrowseTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseTargetActionPerformed(evt);
            }
        });

        jRadioIBM.setFont(new java.awt.Font("Tahoma", 0, 10));
        jRadioIBM.setText("IBM");
        jRadioIBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioIBMActionPerformed(evt);
            }
        });

        jRadioMOSES.setFont(new java.awt.Font("Tahoma", 0, 10));
        jRadioMOSES.setSelected(true);
        jRadioMOSES.setText("MOSES");

        jLabel4.setText("MT system");

        jButtonRun.setText("Run");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jRadioMOSES)
                .addComponent(jRadioIBM)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jCheckBoxLog)
                .addComponent(jLabel1)
                .addComponent(jLabel3)
                .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jRadioGB)
                .addComponent(jRadioBB)
                .addComponent(jRadioBBGB)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jTextTargetFile)
                .addComponent(jTextSourceFile, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jButtonBrowseTarget, 0, 0, Short.MAX_VALUE)
                .addComponent(jButtonBrowseSource, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)))))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jButtonRun)))
                .addContainerGap(225, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jTextSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonBrowseSource))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jButtonBrowseTarget)
                .addComponent(jTextTargetFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jRadioBB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioGB)
                .addGap(3, 3, 3)
                .addComponent(jRadioBBGB)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxLog)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioIBM))
                .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioMOSES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButtonRun)
                .addGap(54, 54, 54)));

        jRadioGB.getAccessibleContext().setAccessibleName("Glass box features only");

        javax.swing.GroupLayout jDialogRunLayout = new javax.swing.GroupLayout(jDialogRun.getContentPane());
        jDialogRun.getContentPane().setLayout(jDialogRunLayout);
        jDialogRunLayout.setHorizontalGroup(
                jDialogRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 572, Short.MAX_VALUE)
                .addGroup(jDialogRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogRunLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())));
        jDialogRunLayout.setVerticalGroup(
                jDialogRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 415, Short.MAX_VALUE)
                .addGroup(jDialogRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogRunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, Short.MAX_VALUE))));

        jDialogConfig.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogConfig.setTitle("Configuration");
        jDialogConfig.setAlwaysOnTop(true);
        jDialogConfig.setMinimumSize(new java.awt.Dimension(500, 414));
        jDialogConfig.setModal(true);
        jDialogConfig.setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSave);

        jButtonSaveAs.setText("Save as");
        jButtonSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAsActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSaveAs);

        jButtonCancel.setText("Cancel");
        jPanel3.add(jButtonCancel);

        jDialogConfig.getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.GridLayout(-1, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Working directory:");
        jPanel4.add(jLabel5);

        jTextDir.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextDir.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDirActionPerformed(evt);
            }
        });
        jPanel4.add(jTextDir);

        jButtonDirChooser.setText("...");
        jButtonDirChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirChooserActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonDirChooser);

        jPanel5.add(jPanel4);

        jLabel6.setText("Default source language: ");
        jPanel6.add(jLabel6);

        jTextSourceLang.setText("Arabic");
        jTextSourceLang.setMinimumSize(new java.awt.Dimension(70, 20));
        jTextSourceLang.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel6.add(jTextSourceLang);

        jPanel5.add(jPanel6);

        jLabel7.setText("Default target language: ");
        jPanel7.add(jLabel7);

        JTextTargetLang.setText("English");
        JTextTargetLang.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel7.add(JTextTargetLang);

        jPanel5.add(jPanel7);

        jLabel8.setText("Default input folder:        ");
        jPanel8.add(jLabel8);

        jTextDefInput.setText("input");
        jTextDefInput.setMinimumSize(new java.awt.Dimension(70, 20));
        jTextDefInput.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel8.add(jTextDefInput);

        jPanel5.add(jPanel8);

        jLabel9.setText("Default output folder:      ");
        jPanel9.add(jLabel9);

        jTextDefOutput.setText("output");
        jTextDefOutput.setMinimumSize(new java.awt.Dimension(70, 20));
        jTextDefOutput.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel9.add(jTextDefOutput);

        jPanel5.add(jPanel9);

        jLabel10.setText("Default log folder:                   ");
        jPanel10.add(jLabel10);

        jTextDefLog.setText("log");
        jTextDefLog.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextDefLog.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel10.add(jTextDefLog);

        jPanel5.add(jPanel10);

        jLabel11.setText("Default resources folder:");
        jPanel11.add(jLabel11);

        jTextField1.setText("lang_resources");
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField1);

        jPanel5.add(jPanel11);

        jTabbedPane2.addTab("Folders", jPanel5);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("Select language: ");
        jPanel12.add(jLabel12);

        jComboLang.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Arabic", "English"}));
        jComboLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLangActionPerformed(evt);
            }
        });
        jPanel12.add(jComboLang);

        jTableLangProp.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Property", "Value"
                }) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTableLangProp.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableLangProp.setMinimumSize(new java.awt.Dimension(300, 50));
        jTableLangProp.setPreferredSize(new java.awt.Dimension(450, 300));
        jTableLangProp.setRowHeight(20);
        jTableLangProp.setRowMargin(5);
        jScrollPane3.setViewportView(jTableLangProp);

        jPanel12.add(jScrollPane3);

        jPanel2.add(jPanel12, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Language specific resources", jPanel2);

        jTableTools.setModel(toTableModel(propManager.getProperties(TOOLS)));
        jScrollPane4.setViewportView(jTableTools);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 494, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)));
        jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 405, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))));

        jTabbedPane2.addTab("Tools and resources", jPanel13);

        jDialogConfig.getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane1.addTab("Features", jScrollPane1);

        jScrollPane2.setViewportView(jEditorPane1);

        jTabbedPane1.addTab("Configuration", jScrollPane2);

        jSplitPaneText.setDividerLocation(270);
        jSplitPaneText.setEnabled(false);

        jScrollPaneSource.setViewportView(jTextPaneSource);

        jSplitPaneText.setRightComponent(jScrollPaneSource);

        jScrollPaneTarget.setViewportView(jTextPaneTarget);

        jSplitPaneText.setLeftComponent(jScrollPaneTarget);

        jTabbedPane1.addTab("Text", jSplitPaneText);

        jScrollPane5.setViewportView(jTextPane3);

        jTabbedPane1.addTab("Output", jScrollPane5);

        jMenuRun.setText("Run");

        jMenuItemRunSimple.setText("Simple run");
        jMenuItemRunSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRunSimpleActionPerformed(evt);
            }
        });
        jMenuRun.add(jMenuItemRunSimple);

        jMenuItemRunClean.setText("Clean run");
        jMenuItemRunClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRunCleanActionPerformed(evt);
            }
        });
        jMenuRun.add(jMenuItemRunClean);

        jMenuBar1.add(jMenuRun);

        jMenuTools.setText("Configuration");

        jMenuItemConfig.setText("Configure");
        jMenuItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuItemConfig);

        jMenuItemClean.setText("Clean");
        jMenuTools.add(jMenuItemClean);

        jMenuBar1.add(jMenuTools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGBActionPerformed
        // TODO add your handling code here:
        mode = "gb";
    }//GEN-LAST:event_jRadioGBActionPerformed

    private void jButtonBrowseTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseTargetActionPerformed
        JFileChooser chooser;
        if (jTextTargetFile.getText().length() > 0) {
            chooser = new JFileChooser(jTextTargetFile.getText());
        } else {
            chooser = new JFileChooser();
        }
        int returnVal = chooser.showOpenDialog(jDialogRun);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jTextTargetFile.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButtonBrowseTargetActionPerformed

    private void jRadioIBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioIBMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioIBMActionPerformed

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
        sourceFile = jTextSourceFile.getText();
        targetFile = jTextTargetFile.getText();
        String[] args;
        if (rebuild) {
            args = new String[]{"-input", sourceFile, targetFile, "-lang", "arabic", "english", "-rebuild", "-mode", mode};
        } else {
            args = new String[]{"-input", sourceFile, targetFile, "-lang", "arabic", "english", "-mode", mode};
        }
        jDialogRun.setVisible(false);
        loadText();
        FeatureExtractor fe = new FeatureExtractor(args);
        fe.run();
    }//GEN-LAST:event_jButtonRunActionPerformed

    private void jRadioBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBBActionPerformed
        // TODO add your handling code here:
        mode = "bb";
    }//GEN-LAST:event_jRadioBBActionPerformed

    private void jRadioBBGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBBGBActionPerformed
        // TODO add your handling code here:
        mode = "all";
    }//GEN-LAST:event_jRadioBBGBActionPerformed

    private void jCheckBoxLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLogActionPerformed
        // TODO add your handling code here:
        log = jCheckBoxLog.isSelected();
    }//GEN-LAST:event_jCheckBoxLogActionPerformed

    private void jMenuItemRunSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRunSimpleActionPerformed
        // TODO add your handling code here:
        rebuild = false;
        jDialogRun.setVisible(true);
    }//GEN-LAST:event_jMenuItemRunSimpleActionPerformed

    private void jMenuItemRunCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRunCleanActionPerformed
        // TODO add your handling code here:
        rebuild = true;
        jDialogRun.setVisible(true);

    }//GEN-LAST:event_jMenuItemRunCleanActionPerformed

    private void jButtonBrowseSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseSourceActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser;
        if (jTextSourceFile.getText().length() > 0) {
            chooser = new JFileChooser(jTextSourceFile.getText());
        } else {
            chooser = new JFileChooser();
        }
        // Note: source for ExampleFileFilter can be found in FileChooserDemo,
        // under the demo/jfc directory in the JDK.
        int returnVal = chooser.showOpenDialog(jDialogRun);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jTextSourceFile.setText(chooser.getSelectedFile().getPath());
        }

    }//GEN-LAST:event_jButtonBrowseSourceActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        workDir = jTextDir.getText();
        System.out.println("Saving config");
        saveConfig(workDir + File.separator + "config.properties");

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jMenuItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigActionPerformed
        jDialogConfig.setVisible(true);
    }//GEN-LAST:event_jMenuItemConfigActionPerformed

    private void jButtonDirChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirChooserActionPerformed
        JFileChooser chooser = new JFileChooser(jTextDir.getText());
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        // Note: source for ExampleFileFilter can be found in FileChooserDemo,
        // under the demo/jfc directory in the JDK.
        int returnVal = chooser.showOpenDialog(jDialogConfig);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jTextDir.setText(chooser.getSelectedFile().getPath());
        }//GEN-LAST:event_jButtonDirChooserActionPerformed
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLangActionPerformed
        String lang = (String) jComboLang.getSelectedItem();
        System.out.println(lang);

        HashMap<String, String> props = propManager.getProperties(lang);
        System.out.println(props);
        jTableLangProp.setModel(toTableModel(props));

    }//GEN-LAST:event_jComboLangActionPerformed

    private void jButtonSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAsActionPerformed
        JFileChooser chooser = new JFileChooser(workDir);
        int returnVal = chooser.showSaveDialog(jDialogConfig);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getPath();
            saveConfig(path);
        }

    }//GEN-LAST:event_jButtonSaveAsActionPerformed

    private void jTextDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDirActionPerformed
        // TODO add your handling code here:
        workDir = jTextDir.getText();
        System.out.println("workDir:" + workDir);
    }//GEN-LAST:event_jTextDirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextTargetLang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBrowseSource;
    private javax.swing.JButton jButtonBrowseTarget;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDirChooser;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSaveAs;
    private javax.swing.JCheckBox jCheckBoxLog;
    private javax.swing.JComboBox jComboLang;
    private javax.swing.JDialog jDialogConfig;
    private javax.swing.JDialog jDialogRun;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemClean;
    private javax.swing.JMenuItem jMenuItemConfig;
    private javax.swing.JMenuItem jMenuItemRunClean;
    private javax.swing.JMenuItem jMenuItemRunSimple;
    private javax.swing.JMenu jMenuRun;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioBB;
    private javax.swing.JRadioButton jRadioBBGB;
    private javax.swing.JRadioButton jRadioMOSES;
    private javax.swing.JRadioButton jRadioGB;
    private javax.swing.JRadioButton jRadioIBM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPaneSource;
    private javax.swing.JScrollPane jScrollPaneTarget;
    private javax.swing.JSplitPane jSplitPaneText;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableLangProp;
    private javax.swing.JTable jTableTools;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextDefInput;
    private javax.swing.JTextField jTextDefLog;
    private javax.swing.JTextField jTextDefOutput;
    private javax.swing.JTextField jTextDir;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPaneSource;
    private javax.swing.JTextPane jTextPaneTarget;
    private javax.swing.JTextField jTextSourceFile;
    private javax.swing.JTextField jTextSourceLang;
    private javax.swing.JTextField jTextTargetFile;
    // End of variables declaration//GEN-END:variables

    private void loadText() {
        try {
            jSplitPaneText.setEnabled(true);
            File file;
            file = new File(sourceFile);
            jTextPaneSource.setPage(file.toURL().toString());
            file = new File(targetFile);
            jTextPaneTarget.setPage(file.toURL().toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static TableModel toTableModel(HashMap<String, String> map) {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Property", "Value"}, 0);
        for (Map.Entry<String, String> entry : map.entrySet()) {
            model.addRow(new Object[]{entry.getKey(), entry.getValue()});
        }
        return model;
    }

    public void saveConfig(String file) {
        saveUserConfig();
        TableModel tm1 = jTableLangProp.getModel();
        int rows = tm1.getRowCount();
        for (int row = 0; row < rows; row++) {
            String key = (String) tm1.getValueAt(row, 0);
            String value = (String) tm1.getValueAt(row, 0);
            propManager.setProperty(key, value);
        }

        try {
            FileWriter fw = new FileWriter(file);
            propManager.store(fw, mode);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
